const GET_API_VERSION = 'GET_API_VERSION';
const USER_AUTH = 'USER_AUTH';
const USER_LOCALE = 'USER_LOCALE';
const USER_LOGOUT = 'USER_LOGOUT';

export { GET_API_VERSION, USER_AUTH, USER_LOCALE, USER_LOGOUT };
